// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package FollowLambdaCompletion.test_import.pkg2

import FollowLambdaCompletion.test_import.pkg1.*

func test1() {
    var a = func1
    var b = AAA11
    var11
    var22
    var c = AAA11()
    c.
}