// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

func add3(abcdefg!: Int64, uuu!: Int64): Int64 {
    return abcdefg + uuu
}

func add3(eee!: Int64, uuu!: Int64, ccc!: String): Int64 {
    return  uuu
}

let c = add3()