// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package my_module

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* char ch = 'a' */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* int a = 0 */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* unsigned int b = 0 */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* short c = 0 */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* unsigned short d = 0 */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* long f = 0 */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* unsigned long g = 0 */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* float x = 1.0 */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* double e = 1.0 */

public const MAX: Int32 = 10
