// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

func add4(abcdefg!: Int64, uuu!: Int64): Int64 {
    return abcdefg + uuu
}

func add4(tttt!: String, uuu!: Int64): Int64 {
    return 2;
}

let d = add4()